# Generated by Django 4.2.30 on 2026-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
    ]
