# Generated by Django 5.2.14 on 2026-05-23 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("favorites", "0002_alter_favorite_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="folder",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="FavoriteFolder",
        ),
    ]
