# Generated by Django 4.2.30 on 2026-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="chapter_number",
            field=models.PositiveIntegerField(db_index=True, verbose_name="章节号"),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(db_index=True, max_length=200, verbose_name="标题"),
        ),
        migrations.AddIndex(
            model_name="chapter",
            index=models.Index(
                fields=["book", "chapter_number"], name="chapter_book_num_idx"
            ),
        ),
    ]
