# Generated by Django 4.2.30 on 2026-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0002_alter_chapter_chapter_number_alter_chapter_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="title",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="章节标题"
            ),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="word_count",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="字数"
            ),
        ),
    ]
