# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
        ('chapters', '0001_initial'),
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_position', models.PositiveIntegerField(default=0, verbose_name='起始位置')),
                ('end_position', models.PositiveIntegerField(default=0, verbose_name='结束位置')),
                ('words_read', models.PositiveIntegerField(default=0, verbose_name='阅读字数')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='阅读时长(秒)')),
                ('reading_speed', models.FloatField(default=0.0, verbose_name='阅读速度(字/分钟)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='books.book', verbose_name='书籍')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_sessions', to='chapters.chapter', verbose_name='章节')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '阅读会话',
                'verbose_name_plural': '阅读会话',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_type', models.CharField(choices=[('daily', '每日统计'), ('weekly', '每周统计'), ('monthly', '每月统计')], max_length=10, verbose_name='统计类型')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('total_words_read', models.PositiveIntegerField(default=0, verbose_name='总阅读字数')),
                ('total_reading_time', models.PositiveIntegerField(default=0, verbose_name='总阅读时长(秒)')),
                ('books_started', models.PositiveIntegerField(default=0, verbose_name='开始阅读书籍数')),
                ('books_finished', models.PositiveIntegerField(default=0, verbose_name='完成阅读书籍数')),
                ('avg_reading_speed', models.FloatField(default=0.0, verbose_name='平均阅读速度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_statistics', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '阅读统计',
                'verbose_name_plural': '阅读统计',
                'ordering': ['-date'],
                'unique_together': {('user', 'stats_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReadingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('words', '字数目标'), ('time', '时长目标'), ('chapters', '章节目标')], max_length=10, verbose_name='目标类型')),
                ('target_value', models.PositiveIntegerField(verbose_name='目标值')),
                ('current_value', models.PositiveIntegerField(default=0, verbose_name='当前值')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_goals', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '阅读目标',
                'verbose_name_plural': '阅读目标',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['user', 'date'], name='session_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='readingsession',
            index=models.Index(fields=['user', 'book'], name='session_user_book_idx'),
        ),
        migrations.AddIndex(
            model_name='readingstatistics',
            index=models.Index(fields=['user', 'stats_type', 'date'], name='stats_user_type_date_idx'),
        ),
    ]
