# Generated by Django 6.0.5 on 2026-05-21 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0002_alter_readingprogress_chapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReadingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "read_seconds",
                    models.PositiveIntegerField(default=0, verbose_name="阅读秒数"),
                ),
                (
                    "chapters_read",
                    models.PositiveIntegerField(default=0, verbose_name="阅读章节数"),
                ),
                (
                    "words_read",
                    models.PositiveIntegerField(default=0, verbose_name="阅读字数"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "阅读统计",
                "verbose_name_plural": "阅读统计",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
