# Generated by Django 4.2.30 on 2026-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0003_readingstats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readingprogress",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="readingstats",
            name="date",
            field=models.DateField(db_index=True, verbose_name="日期"),
        ),
    ]
