# Generated by Django 4.2.30 on 2026-05-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="书名"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, verbose_name="作者"
                    ),
                ),
                (
                    "folder_path",
                    models.CharField(
                        max_length=500, unique=True, verbose_name="文件夹路径"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "total_chapters",
                    models.PositiveIntegerField(default=0, verbose_name="总章节数"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "书籍",
                "verbose_name_plural": "书籍",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名"),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=7, verbose_name="颜色"),
                ),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
            },
        ),
        migrations.CreateModel(
            name="BookTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="书籍",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.tag",
                        verbose_name="标签",
                    ),
                ),
            ],
            options={
                "verbose_name": "书籍标签",
                "verbose_name_plural": "书籍标签",
                "unique_together": {("book", "tag")},
            },
        ),
    ]
