# Generated by Django 4.2.30 on 2026-05-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookTag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
