# Generated by Django 4.2.30 on 2026-05-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_delete_booktag_delete_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="分类"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["author", "created_at"], name="book_author_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["category", "created_at"], name="book_category_created_idx"
            ),
        ),
    ]
