# Generated by Django 4.2.30 on 2026-05-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_tag_book_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_index=True, verbose_name="更新时间"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                db_index=True, max_length=30, unique=True, verbose_name="标签名"
            ),
        ),
    ]
